### ISSUE TITLE
“Active” comment jumps to the right

### ISSUE THREAD

**Issue by llelf** [evanrelf/r-haskell-theme#4]
I think the cause is `border-left` in `div.RES-keyNav-activeElement`

**Comment by evanrelf** [comment]
The CSS selector has the acronym `RES` in it, which means that it was probably created by the [Reddit Enhancement Suite](http://redditenhancementsuite.com) browser extension. RES allows you to navigate between posts with the <kbd>J</kbd> and <kbd>K</kbd> keys.

If you do not use RES's keyboard navigation you can stop the active comment from jumping to the right:

1. Hover over the cog/gear icon in the top right corner of the page and choose "RES settings console"
2. Click on "UI" in the navigation bar
3. In the sidebar, click on "Keyboard Navigation" (3rd item from the top)
4. Toggle the topmost ON/OFF switch next to where it says "Keyboard Navigation"
